/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedUploadRouteImport } from './routes/_authenticated/upload'
import { Route as AuthenticatedProjectsRouteImport } from './routes/_authenticated/projects'
import { Route as AuthenticatedProjectLeadRouteImport } from './routes/_authenticated/project-lead'
import { Route as AuthenticatedPeBoardRouteImport } from './routes/_authenticated/pe-board'
import { Route as AuthenticatedOpcoRouteImport } from './routes/_authenticated/opco'
import { Route as AuthenticatedForecastRouteImport } from './routes/_authenticated/forecast'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCfoRouteImport } from './routes/_authenticated/cfo'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUploadRoute = AuthenticatedUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProjectsRoute = AuthenticatedProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProjectLeadRoute =
  AuthenticatedProjectLeadRouteImport.update({
    id: '/project-lead',
    path: '/project-lead',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPeBoardRoute = AuthenticatedPeBoardRouteImport.update({
  id: '/pe-board',
  path: '/pe-board',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOpcoRoute = AuthenticatedOpcoRouteImport.update({
  id: '/opco',
  path: '/opco',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedForecastRoute = AuthenticatedForecastRouteImport.update({
  id: '/forecast',
  path: '/forecast',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCfoRoute = AuthenticatedCfoRouteImport.update({
  id: '/cfo',
  path: '/cfo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cfo': typeof AuthenticatedCfoRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/forecast': typeof AuthenticatedForecastRoute
  '/opco': typeof AuthenticatedOpcoRoute
  '/pe-board': typeof AuthenticatedPeBoardRoute
  '/project-lead': typeof AuthenticatedProjectLeadRoute
  '/projects': typeof AuthenticatedProjectsRoute
  '/upload': typeof AuthenticatedUploadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cfo': typeof AuthenticatedCfoRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/forecast': typeof AuthenticatedForecastRoute
  '/opco': typeof AuthenticatedOpcoRoute
  '/pe-board': typeof AuthenticatedPeBoardRoute
  '/project-lead': typeof AuthenticatedProjectLeadRoute
  '/projects': typeof AuthenticatedProjectsRoute
  '/upload': typeof AuthenticatedUploadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/cfo': typeof AuthenticatedCfoRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/forecast': typeof AuthenticatedForecastRoute
  '/_authenticated/opco': typeof AuthenticatedOpcoRoute
  '/_authenticated/pe-board': typeof AuthenticatedPeBoardRoute
  '/_authenticated/project-lead': typeof AuthenticatedProjectLeadRoute
  '/_authenticated/projects': typeof AuthenticatedProjectsRoute
  '/_authenticated/upload': typeof AuthenticatedUploadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/cfo'
    | '/dashboard'
    | '/forecast'
    | '/opco'
    | '/pe-board'
    | '/project-lead'
    | '/projects'
    | '/upload'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/cfo'
    | '/dashboard'
    | '/forecast'
    | '/opco'
    | '/pe-board'
    | '/project-lead'
    | '/projects'
    | '/upload'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/cfo'
    | '/_authenticated/dashboard'
    | '/_authenticated/forecast'
    | '/_authenticated/opco'
    | '/_authenticated/pe-board'
    | '/_authenticated/project-lead'
    | '/_authenticated/projects'
    | '/_authenticated/upload'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/upload': {
      id: '/_authenticated/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof AuthenticatedUploadRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects': {
      id: '/_authenticated/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AuthenticatedProjectsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/project-lead': {
      id: '/_authenticated/project-lead'
      path: '/project-lead'
      fullPath: '/project-lead'
      preLoaderRoute: typeof AuthenticatedProjectLeadRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pe-board': {
      id: '/_authenticated/pe-board'
      path: '/pe-board'
      fullPath: '/pe-board'
      preLoaderRoute: typeof AuthenticatedPeBoardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/opco': {
      id: '/_authenticated/opco'
      path: '/opco'
      fullPath: '/opco'
      preLoaderRoute: typeof AuthenticatedOpcoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/forecast': {
      id: '/_authenticated/forecast'
      path: '/forecast'
      fullPath: '/forecast'
      preLoaderRoute: typeof AuthenticatedForecastRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cfo': {
      id: '/_authenticated/cfo'
      path: '/cfo'
      fullPath: '/cfo'
      preLoaderRoute: typeof AuthenticatedCfoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCfoRoute: typeof AuthenticatedCfoRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedForecastRoute: typeof AuthenticatedForecastRoute
  AuthenticatedOpcoRoute: typeof AuthenticatedOpcoRoute
  AuthenticatedPeBoardRoute: typeof AuthenticatedPeBoardRoute
  AuthenticatedProjectLeadRoute: typeof AuthenticatedProjectLeadRoute
  AuthenticatedProjectsRoute: typeof AuthenticatedProjectsRoute
  AuthenticatedUploadRoute: typeof AuthenticatedUploadRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCfoRoute: AuthenticatedCfoRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedForecastRoute: AuthenticatedForecastRoute,
  AuthenticatedOpcoRoute: AuthenticatedOpcoRoute,
  AuthenticatedPeBoardRoute: AuthenticatedPeBoardRoute,
  AuthenticatedProjectLeadRoute: AuthenticatedProjectLeadRoute,
  AuthenticatedProjectsRoute: AuthenticatedProjectsRoute,
  AuthenticatedUploadRoute: AuthenticatedUploadRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
